### ISSUE TITLE
[BUG] bot minecraft non finisce il suo comando

### ISSUE THREAD

**Issue by ZzGodlyy** [sleeyax/aternos-discord-bot#54] opened 2022-08-01 10:03 UTC
ho settato il bot, ho messo aternos session e server pero appena faccio /start il server si avvia pero poi su discord non esce scritto che il server e on

**Comment by sleeyax** [comment] 2022-08-01 10:05
English please. I don't understand what you're saying.

**Comment by ZzGodlyy** [comment] 2022-08-01 10:05
I set up the bot, I put aternos session and server but as soon as I do / start the server starts but then on discord it does not come out written that the server is on

**Comment by ZzGodlyy** [comment] 2022-08-01 10:06
I also tried reloading the page

**Comment by ZzGodlyy** [comment] 2022-08-01 10:19
indeed, now it no longer responds to commands

**Comment by sleeyax** [comment] 2022-08-01 10:21
I need more information. Are you self hosting the bot or setting up the demo?

**Comment by ZzGodlyy** [comment] 2022-08-01 11:13
bro

**Comment by ZzGodlyy** [comment] 2022-08-01 11:15
I have set the bot but after I do / start it tells me WAIT A MOMENT THE SERVER IS STARTING then go to aternos and the server is started but it does not appear written on discord that the server has started, in a few words to see if the server and on I have to open aternos

**Comment by ZzGodlyy** [comment] 2022-08-01 11:34
?

**Comment by sleeyax** [comment] 2022-08-01 11:39
I just tried on my end and it works fine. Since you still haven't provided any more information I can only guess what's going on at your end. 

Close aternos (but DONT logout!) in the browser and start the bot again from discord; I don't think you get the notification in discord if you have aternos open in your browser already.

**Comment by ZzGodlyy** [comment] 2022-08-01 11:42
I had already closed aternos but does not respond the same to the command

**Comment by ZzGodlyy** [comment] 2022-08-01 13:22
![image](https://user-images.githubusercontent.com/110388950/182157584-eb032177-6f3a-4fd6-9ba0-1ab2e657eb00.png)

**Comment by ZzGodlyy** [comment] 2022-08-01 13:41
pls help meeeeeeeeee

**Comment by ZzGodlyy** [comment] 2022-08-01 13:44
![image](https://user-images.githubusercontent.com/110388950/182161482-c82d3762-359f-4082-8d44-1a26f80f5124.png)

**Comment by sleeyax** [comment] 2022-08-01 13:55
Spamming the bot or this GitHub issue doesn't help ¯\_(ツ)_/¯

**Comment by sleeyax** [comment] 2022-08-03 23:51
@ZzGodlyy are you still experiencing your initial issue (no discord notification after `/start`)? It could be related to the aternos queue, which is hard to debug because it depends on the server location. The problem might 'fix' itself when there's not many players around.

**Comment by sleeyax** [comment] 2022-08-11 21:43
Closing this because I can't reproduce this issue and as not enough information is provided to debug this further.

**Closed by sleeyax** 2022-08-11 21:43 UTC
Labels: bug
