### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AUUUUUUUUUGH** [sleeyax/aternos-discord-bot#48] opened 2022-06-10 14:10 UTC
1. When i am configure it is saying this:
<img width="352" alt="Screenshot 2022-06-10 at 16 08 00" src="https://user-images.githubusercontent.com/107212717/173083762-3e642304-787b-4d2d-83f7-2f456d68e836.png">
2. But when i am writing "/start" it is saying this
<img width="549" alt="Screenshot 2022-06-10 at 16 08 46" src="https://user-images.githubusercontent.com/107212717/173083917-e4a2b1df-98c0-41a4-a776-78724da09284.png">
3. When I reconfigure the bot it is starting from the first step...

**Comment by sleeyax** [comment] 2022-06-10 19:02
Duplicate of #44

**Closed by sleeyax** 2022-06-10 19:02 UTC
Labels: bug
