### ISSUE TITLE
When I try using it in docker desktop, it doesn't work.

### ISSUE THREAD

**Issue by alanadiamondpearl** [sleeyax/aternos-discord-bot#2] opened 2022-02-16 02:01 UTC
I don't really know what to do.

**Comment by sleeyax** [comment] 2022-02-16 08:21
Start by telling what goes wrong.  'it doesn't work' doesn't help me at all. 

Make sure to replace the environment variables (-e) with your cookies etc.

**Comment by sleeyax** [comment] 2022-03-26 01:11
Closing because of lack of information to reproduce this issue.

**Closed by sleeyax** 2022-03-26 01:11 UTC
