### ISSUE TITLE
[BUG] ❌ Invalid credentials. Use /configure to reconfigure the bot.

### ISSUE THREAD

**Issue by Aumika** [sleeyax/aternos-discord-bot#55] opened 2022-08-02 11:10 UTC
Whenever i do /configure and then /start or any other command it says invalid credentials. but the session id and server is correct.  i followed steps in video

**Comment by sleeyax** [comment] 2022-08-03 23:47
Duplicate of #44

**Closed by sleeyax** 2022-08-03 23:47 UTC
Labels: bug
